script:
  - npm test --single-run
  - node_modules/.bin/protractor ./test/e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 3